global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'job-scheduler'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
  - job_name: 'pushgateway'
    honor_labels: true  #  scrape config for Pushgateway
    static_configs:
      - targets: ['localhost:9091']